import { create } from 'zustand';
// import { persist } from 'zustand/middleware';

type Language = 'es' | 'en';

interface LanguageState {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

// @ts-ignore
const translations: any = {
    es: {
        // Sidebar
        'nav.home': 'Principal',
        'nav.upload': 'Subir RFQ',
        'nav.table': 'Tabla Datos',
        'nav.qa': 'Q&A Offers',
        'nav.decision': 'Scoring',
        'nav.chat': 'Chat',
        'nav.mail': 'Email AI',
        'nav.footer': 'v2.1 Beta',

        // Header
        'header.home': 'Resumen Principal',
        'header.upload': 'Gestión de RFQs y Propuestas',
        'header.table': 'Explorador de Datos',
        'header.qa': 'Q&A y Aclaraciones de Ofertas',
        'header.decision': 'Análisis de Scoring',
        'header.chat': 'Asistente IA',
        'header.mail': 'Generador de Comunicaciones',

        // Home Dashboard
        'home.hero.title': 'BidEval',
        'home.hero.subtitle': 'Sistema de Evaluación de Ofertas',
        'home.hero.desc': 'Evaluación de ofertas potenciada con IA. Análisis inteligente, scoring automatizado y decisiones basadas en datos.',
        'home.hero.btn_new': '+ Nueva RFQ',
        'home.hero.btn_reports': 'Ver Reportes',

        'home.stats.proposals': 'Propuestas Procesadas',
        'home.stats.active': 'Proyectos Activos',
        'home.stats.efficiency': 'Eficiencia IA',
        'home.stats.trend_week': '+2 esta semana',
        'home.stats.trend_course': 'En curso',
        'home.stats.trend_high': 'Precisión alta',

        'home.chart.title': 'Estado de Cumplimiento Técnico',
        'home.chart.subtitle': 'Últimos 30 días',
        'home.chart.evaluations_by_provider': 'Evaluaciones por Proveedor',
        'home.chart.distribution': 'Distribución de estados en ofertas',

        'home.activity.title': 'Actividad Reciente',
        'home.activity.offer_received': 'Oferta Recibida',
        'home.activity.offer_desc': 'Propuesta técnica revisada automáticamente.',
        'home.activity.alert': 'Alerta de Cumplimiento',
        'home.activity.alert_desc': 'falta sección de seguridad HSE.',
        'home.activity.created': 'Nuevo RFQ Creado',
        'home.activity.created_desc': 'Proyecto Hidrógeno Verde - Fase 2',
        'home.activity.user': 'Usuario conectado',
        'home.activity.ago_2h': 'Hace 2 horas',
        'home.activity.ago_5h': 'Hace 5 horas',
        'home.activity.yesterday': 'Ayer',
        'home.activity.days_ago': 'días atrás',
        'home.activity.just_now': 'Ahora mismo',
        'home.activity.proposal_evaluated': 'Propuesta evaluada',
        'home.activity.qa_update': 'Actualización Q&A',
        'home.activity.qa_activity': 'Actividad en módulo Q&A',
        'home.activity.recent_activity': 'Actividad reciente',
        'home.activity.no_activity': 'Sin actividad reciente',
        'home.activity.supplier_responded': 'Respuesta de Proveedor',
        'home.activity.questions_sent': 'Preguntas Enviadas',
        'home.activity.evaluation_updated': 'Evaluación Actualizada',
        'home.activity.response_received': 'respuesta(s) recibida(s)',

        // Dashboard cards
        'home.card.total_processed': 'Propuestas Procesadas',
        'home.card.rfqs_processed': 'RFQs Procesadas',
        'home.card.ai_accuracy': 'Precisión IA',
        'home.card.automation': 'Automatización',
        'home.card.this_week': 'esta semana',
        'home.card.proposals': 'propuestas',
        'home.card.coverage': 'cobertura',
        'home.card.excellent_performance': 'Excelente rendimiento',
        'home.card.very_high': 'Muy alto',
        'home.card.avg_time': 'Tiempo Promedio',
        'home.card.completed_today': 'Completadas Hoy',
        'home.card.active_providers': 'Proveedores Activos',

        // AI Scoring section
        'home.scoring.title': 'Scoring IA por Proveedor',
        'home.scoring.subtitle': 'Puntuaciones ponderadas del workflow',
        'home.scoring.top_performer': 'Mejor Rendimiento',
        'home.scoring.avg_score': 'Puntuación Promedio',
        'home.scoring.compliance_rate': 'Tasa de Cumplimiento',
        'home.scoring.providers_evaluated': 'Proveedores Evaluados',
        'home.scoring.no_data': 'Sin datos de scoring. Ejecuta el Scoring IA para generar resultados.',
        'home.scoring.technical': 'Técnico',
        'home.scoring.economic': 'Económico',
        'home.scoring.execution': 'Ejecución',
        'home.scoring.hse': 'HSE',

        // Vendor Decision Dashboard
        'dashboard.title': 'Dashboard de Scoring de Proveedores',
        'dashboard.rfq_id': 'ID RFQ',
        'dashboard.tab.clarification': 'Aclaraciones y EyR',
        'dashboard.tab.scoring': 'Matriz de Puntuación',
        'dashboard.tab.executive': 'Resumen Ejecutivo',
        'dashboard.loading': 'Cargando Análisis de Scoring...',
        // Clarification View
        'clarification.filter': 'Filtrar por Proveedor',
        'clarification.table.req': 'Requisito',
        'clarification.table.resp': 'Respuesta del Proveedor',
        'clarification.table.comp': 'Cumplimiento',
        'clarification.table.actions': 'Aclaraciones y Acciones',
        'clarification.btn.send': 'Enviar Pregunta',
        'clarification.btn.approve': 'Aprobar Pregunta',
        'clarification.btn.resolve': 'Marcar Resuelto',
        'clarification.status.resolved': '✓ Resuelto',
        'clarification.export': 'Exportar Hoja EyR (.xlsx)',

        // Scoring View
        'scoring.req': 'Requisito',
        'scoring.weight': 'Peso',
        'scoring.total': 'Puntuación Ponderada',

        // Executive View
        'executive.winner': 'Ganador Recomendado',
        'executive.score': 'Puntuación',
        'executive.award': 'Adjudicar Contrato',
        'executive.radar.title': 'Comparación por Categorías',
        'executive.bar.title': 'Puntuaciones Finales Ponderadas',
        'executive.radar.subtitle': 'Comparación multidimensional por categoría',
        'executive.bar.subtitle': 'Puntuación total ponderada',
        'executive.calculating': 'Calculando Puntuaciones IA...',
        'executive.calculating_subtitle': 'Evaluando proveedores en 12 criterios. Esto puede tardar un momento.',
        'executive.no_data': 'No hay datos de scoring disponibles. Ejecuta el workflow de scoring para generar resultados.',
        'executive.refresh': 'Actualizar Datos',
        'executive.lead_margin': 'Margen de Ventaja vs',
        'executive.pts': 'pts',
        'executive.advantage': 'ventaja',
        'executive.key_strengths': 'Fortalezas Clave',
        'executive.no_strengths': 'Sin categorías dominantes',
        'executive.areas_review': 'Áreas a Revisar',
        'executive.no_data_available': 'Sin datos disponibles',
        'executive.top_rankings': 'Ranking Top',
        'executive.criteria_weight': 'Distribución de Pesos por Criterio',
        'executive.scoring_impact': 'Impacto del scoring por categoría',
        'executive.weight': 'Peso',
        'executive.contract_awarded': 'Contrato adjudicado a',
        'executive.total_score': 'Puntuación Total',
        // Category names
        'category.technical': 'TÉCNICO',
        'category.economic': 'ECONÓMICO',
        'category.execution': 'EJECUCIÓN',
        'category.hse_compliance': 'HSE Y CUMPLIMIENTO',
        // Criteria labels
        'criteria.scope_facilities': 'Alcance de Instalaciones',
        'criteria.scope_work': 'Alcance de Trabajo',
        'criteria.deliverables_quality': 'Calidad de Entregables',
        'criteria.total_price': 'Precio Total',
        'criteria.price_breakdown': 'Desglose de Precios',
        'criteria.optionals_included': 'Opcionales Incluidos',
        'criteria.capex_opex_methodology': 'Metodología CAPEX/OPEX',
        'criteria.schedule': 'Cronograma',
        'criteria.resources_allocation': 'Asignación de Recursos',
        'criteria.exceptions': 'Excepciones',
        'criteria.safety_studies': 'Estudios de Seguridad',
        'criteria.regulatory_compliance': 'Cumplimiento Regulatorio',
        // Criteria descriptions
        'criteria.scope_facilities.desc': 'Planta de hidrógeno, BOP, servicios incluidos',
        'criteria.scope_work.desc': 'Gestión de proyecto, estudios, entregables cubiertos',
        'criteria.deliverables_quality.desc': 'P&IDs, especificaciones, calidad del modelo 3D',
        'criteria.total_price.desc': 'Competitividad de precio PRE-FEED + FEED + EPC',
        'criteria.price_breakdown.desc': 'Horas/disciplina y €/hora transparentes',
        'criteria.optionals_included.desc': 'Geotécnico, topográfico, 3D, HAZID en precio base',
        'criteria.capex_opex_methodology.desc': 'Clase AACEI ofrecida, robustez del estimado',
        'criteria.schedule.desc': 'Cronograma realista vs requisitos',
        'criteria.resources_allocation.desc': 'Horas coherentes por disciplina',
        'criteria.exceptions.desc': 'Menos excepciones y desviaciones = mejor',
        'criteria.safety_studies.desc': 'HAZID, HAZOP, QRA, ATEX incluidos',
        'criteria.regulatory_compliance.desc': 'Códigos, estándares, distancias de seguridad',
        // Scoring matrix categories
        'scoring.category.technical': 'TÉCNICO',
        'scoring.category.economic': 'ECONÓMICO',
        'scoring.category.execution': 'EJECUCIÓN',
        'scoring.category.hse_compliance': 'HSE Y CUMPLIMIENTO',

        // Upload & App
        'upload.error.file_size': 'archivo(s) demasiado grande(s). Máximo',
        'upload.confirm.delete': '¿Estás seguro de que deseas eliminar la RFQ base cargada?',
        'upload.rfq_loaded': 'RFQ Cargada',
        'upload.processed_types': 'Tipos',
        'upload.change_rfq': 'Cambiar RFQ',
        'upload.rfq_hint': 'Los requisitos de esta RFQ se usarán para comparar con las ofertas de proveedores',
        'upload.modal.replace_title': '¿Reemplazar RFQ actual?',
        'upload.modal.current': 'Ya tienes una RFQ cargada',
        'upload.modal.replace_bg': '¿Deseas reemplazarla con',
        'upload.files': 'archivos RFQ',
        'upload.btn.replace': 'Sí, reemplazar',
        'upload.btn.cancel': 'Cancelar',
        'upload.status.processing': 'Procesando RFQ... Esto puede tardar unos minutos',
        'upload.files_selected': 'archivos seleccionados',
        'upload.drop_here': 'Suelta los archivos PDF aquí...',
        'upload.drag_drop': 'Arrastra y suelta PDFs de RFQ aquí, o haz clic para seleccionar',
        'upload.view_files': 'Ver archivos',
        'upload.status.error': 'Error',
        'upload.file': 'archivo',
        'upload.btn.process': 'Procesar',
        'upload.btn.reset': 'Reiniciar',
        'upload.modal.files_title': 'Archivos RFQ Seleccionados',
        'upload.btn.close': 'Cerrar',
        'upload.btn.remove': 'Eliminar archivo',
        'upload.btn.clear_all': 'Borrar todos los archivos',
        'app.upload.tab.rfq': '1. Subir RFQ de Referencia',
        'app.upload.tab.proposals': '2. Subir Propuestas de Proveedores',
        'app.upload.supported_providers': 'Proveedores soportados: Técnicas Reunidas, IDOM, SACYR, Empresarios Agrupados, SENER, TRESCA, WORLEY',
        'common.error': 'Error',
        'upload.proposals': 'Propuestas',
        'common.reset': 'Reiniciar',
        'app.table.no_data': 'No hay datos procesados todavía. Ve a la sección de "Subir y Procesar" para comenzar.',
        'chat.placeholder': 'Escribe tu pregunta aquí...',

        // Mail Dashboard
        'mail.config': 'Configuración de Correo',
        'mail.project': 'Proyecto',
        'mail.provider': 'Proveedor Destinatario',
        'mail.provider.select': 'Seleccionar Proveedor...',
        'mail.tone': 'Tono',
        'mail.tone.formal': 'Formal',
        'mail.tone.urgent': 'Urgente',
        'mail.tone.friendly': 'Amigable',
        'mail.btn.drafting': 'Redactando...',
        'mail.btn.regenerate': 'Regenerar Borrador',
        'mail.btn.generate': 'Generar Borrador',
        'mail.empty.title': 'Listo para Redactar',
        'mail.empty.desc': 'Selecciona un proveedor para generar un borrador de correo profesional impulsado por IA.',
        'mail.preview.markdown': 'Markdown',
        'mail.preview.text': 'Texto',
        'mail.btn.discard': 'Descartar',
        'mail.btn.copy': 'Copiar al Portapapeles',
        'mail.preview.header': 'Vista Previa',
        'mail.preview.to': 'Para:',
        'mail.preview.subject': 'Asunto:',
        'mail.tech_questions': 'Preguntas Técnicas',
        'mail.btn.all': 'Todas',
        'mail.btn.none': 'Ninguna',
        'mail.no_qa_items': 'Sin preguntas Q&A para',
        'mail.other_items': 'preguntas para otros proveedores',
        'mail.ai_drafting': 'El agente IA está redactando tu correo...',
        'mail.analyzing': 'Analizando contexto y formateando incidencias',
        'mail.generation_failed': 'Generación Fallida',
        'mail.generation_failed_desc': 'Error al generar el borrador. Por favor, intenta de nuevo.',
        'mail.btn.done': 'Hecho',
        'mail.btn.edit': 'Editar',
        'mail.btn.send': 'Enviar Correo',
        'mail.btn.sending': 'Enviando...',
        'mail.btn.sent': 'Enviado!',
        'mail.btn.copy_short': 'Copiar',
        'mail.tone_label': 'Tono',
        'mail.alert.enter_email': 'Por favor, ingresa un correo electrónico válido en el campo "Para".',
        'mail.alert.confirm_send': '¿Enviar correo a',
        'mail.alert.copy_success': 'Correo copiado al portapapeles!',
        'mail.alert.send_success': 'Correo enviado exitosamente!',
        'mail.alert.send_failed': 'Error al enviar el correo. Por favor, intenta de nuevo o copia y envía manualmente.',
        'mail.recipient_placeholder': 'destinatario@email.com',

        // Analysis Columns
        'table.col.requirement': 'Requisito',
        'table.col.phase': 'Fase',
        'table.col.evaluation': 'Evaluación',
        'table.col.description': 'Descripción del Ítem',

        // Tour / Onboarding
        'tour.welcome.title': 'Bienvenido a BidEval',
        'tour.welcome.description': 'Te guiaremos por las principales funcionalidades de la plataforma para que puedas sacar el máximo provecho.',
        'tour.sidebar.title': 'Navegación Principal',
        'tour.sidebar.description': 'Este es el menú lateral donde encontrarás acceso a todos los módulos. Puedes expandirlo o contraerlo. Los indicadores visuales señalan módulos con sesiones activas.',
        'tour.home.title': 'Panel Principal',
        'tour.home.description': 'Aquí verás un resumen de tu actividad: métricas, estadísticas y actividad reciente de tus proyectos.',
        'tour.upload.title': 'Subir Documentos',
        'tour.upload.description': 'Carga tus RFQs de referencia y las propuestas de proveedores. El sistema procesará y extraerá automáticamente los requisitos.',
        'tour.table.title': 'Explorador de Datos',
        'tour.table.description': 'Visualiza y explora todos los datos procesados en formato de tabla con filtros avanzados y opciones de exportación.',
        'tour.qa.title': 'Q&A de Ofertas',
        'tour.qa.description': 'Gestiona las preguntas y aclaraciones pendientes sobre las ofertas de los proveedores.',
        'tour.decision.title': 'Análisis de Scoring',
        'tour.decision.description': 'Matriz de puntuación con análisis comparativo de proveedores. Ajusta pesos y visualiza el ranking final.',
        'tour.chat.title': 'Asistente IA',
        'tour.chat.description': 'Conversa con nuestro asistente inteligente para obtener respuestas rápidas sobre tus RFQs y propuestas.',
        'tour.mail.title': 'Generador de Emails',
        'tour.mail.description': 'Genera borradores de correos profesionales con IA basados en las aclaraciones pendientes de cada proveedor.',
        'tour.project.title': 'Selección de Proyecto',
        'tour.project.description': 'Aquí puedes cambiar entre tus distintos proyectos activos. Al cambiar de proyecto, toda la información del dashboard se actualizará correspondientemente.',
        'tour.header.title': 'Configuración Rápida',
        'tour.header.description': 'Cambia el idioma, alterna entre modo claro y oscuro, y accede a tu perfil desde aquí.',
        'tour.finish.title': '¡Listo para comenzar!',
        'tour.finish.description': 'Ya conoces las funcionalidades principales. Puedes reiniciar este tour en cualquier momento desde el menú de ayuda.',
        'tour.btn.next': 'Siguiente',
        'tour.btn.back': 'Atrás',
        'tour.btn.skip': 'Omitir tour',
        'tour.btn.finish': 'Finalizar',
        'tour.btn.close': 'Cerrar',
        'tour.btn.restart': 'Reiniciar Tour',

        // Notifications
        'notifications.title': 'Notificaciones',
        'notifications.markAllRead': 'Marcar todo como leído',
        'notifications.clearAll': 'Borrar todo',
        'notifications.delete': 'Eliminar',
        'notifications.empty': 'No hay notificaciones',
        'notifications.supplierResponded': 'El proveedor ha respondido',
        'notifications.evaluationUpdated': 'Evaluación actualizada',
        'notifications.questionsSent': 'Preguntas enviadas',

        // QA Module
        'qa.title': 'Gestión de Q&A',
        'qa.subtitle': 'Genera preguntas inteligentes y gestiona auditorías técnicas',
        'qa.generator.title': 'Generador de Auditoría Técnica',
        'qa.generator.subtitle': 'Genera preguntas con IA basadas en deficiencias del proveedor',
        'qa.generator.project': 'Proyecto',
        'qa.generator.provider': 'Proveedor',
        'qa.generator.select_project': 'Seleccionar proyecto...',
        'qa.generator.select_provider': 'Seleccionar Proveedor',
        'qa.generator.btn_generate': 'Generar Auditoría Técnica',
        'qa.generator.btn_generating': 'Generando Auditoría...',
        'qa.generator.btn_export': 'Exportar a Excel',
        'qa.generator.status_analyzing': 'Analizando deficiencias y generando preguntas de auditoría técnica...',
        'qa.questions.title': 'Gestión de Preguntas',
        'qa.questions.subtitle': 'Ver y gestionar preguntas generadas por disciplina',
        'qa.questions.btn_send': 'Enviar a Proveedor',
        'qa.questions.btn_sending': 'Enviando...',
        'qa.questions.btn_export_all': 'Exportar Todas las Preguntas',
        'qa.questions.btn_filters': 'Filtros',
        'qa.questions.total': 'Preguntas Totales',
        'qa.questions.approved': 'Aprobadas',
        'qa.questions.pending': 'Pendientes',
        'qa.questions.high_importance': 'Alta Importancia',
        'qa.questions.no_questions': 'No hay preguntas generadas',
        'qa.questions.no_questions_hint': 'Selecciona un proyecto y proveedor, luego haz clic en "Generar Auditoría Técnica"',
        'qa.questions.add_question': '+ Añadir otra pregunta',
        'qa.questions.write_question': 'Escribe tu pregunta aquí...',
        'qa.questions.view_source': 'Ver requisito origen',
        'qa.questions.loading_req': 'Cargando requisito...',
        'qa.question.response': 'Respuesta:',
        'qa.question.answered_on': 'Respondido el',
        'qa.question.internal_notes': 'Notas internas:',
        'qa.btn.edit': 'Editar',
        'qa.btn.save': 'Guardar',
        'qa.btn.cancel': 'Cancelar',
        'qa.btn.approve': 'Aprobar',
        'qa.btn.discard': 'Descartar',
        'qa.btn.send': 'Enviar',
        'qa.btn.accept_response': 'Aceptar Respuesta',
        'qa.btn.need_more_info': 'Necesita Más Info',
        'qa.btn.mark_resolved': 'Marcar Resuelto',
        'qa.status.waiting': 'Esperando respuesta...',
        'qa.status.review_needed': 'Respuesta recibida - Revisión necesaria',
        'qa.status.resolved': '✓ Respuesta aceptada - Problema resuelto',
        'qa.status.more_info': 'Se solicitó información adicional',
        'qa.status.discarded': 'Descartada',
        // Thread/Conversation translations
        'qa.thread.follow_up': 'Pregunta de Seguimiento',
        'qa.thread.write_follow_up': 'Escribe tu pregunta de seguimiento basada en la respuesta del proveedor...',
        'qa.thread.send_follow_up': 'Enviar Seguimiento',
        'qa.thread.conversation': 'Conversación',
        'qa.thread.original_question': 'Pregunta Original',
        'qa.thread.resolved': 'Hilo Resuelto',
        'qa.thread.follow_up_label': 'Seguimiento',
        'qa.thread.view_thread': 'Ver conversación',
        'qa.thread.collapse_thread': 'Ocultar conversación',
        'qa.thread.created_draft': 'Pregunta de seguimiento creada como borrador. Apruébala y envíala junto con otras.',
        'qa.thread.view_history': 'Ver historial de conversación',
        'qa.thread.hide_history': 'Ocultar hilo',
        'qa.thread.previous_question': 'Pregunta',
        'qa.thread.previous_response': 'Respuesta del proveedor',
        'qa.thread.no_response_yet': 'Sin respuesta aún',
        'qa.thread.current_question': 'Pregunta actual (abajo)',
        'qa.thread.no_history': 'No se pudo cargar el historial',
        'qa.badge.original': 'Original',
        'qa.filters.title': 'Filtros de Búsqueda',
        'qa.filters.clear': 'Limpiar Todo',
        'qa.filters.provider': 'Proveedor',
        'qa.filters.all_providers': 'Todos los Proveedores',
        'qa.filters.status': 'Estado',
        'qa.filters.all_statuses': 'Todos los Estados',
        'qa.filters.importance': 'Importancia',
        'qa.filters.all_importances': 'Todas las Importancias',
        'qa.modal.success_title': 'Preguntas Enviadas Exitosamente',
        'qa.modal.success_subtitle': 'El cuestionario ha sido preparado para',
        'qa.modal.questions': 'Preguntas',
        'qa.modal.provider': 'Proveedor',
        'qa.modal.expires': 'Expira',
        'qa.modal.link_label': 'Enlace de Respuesta (compartir con proveedor)',
        'qa.modal.link_hint': 'Envía este enlace al proveedor. Pueden acceder al cuestionario y enviar sus respuestas.',
        'qa.modal.email_preview': 'Vista Previa del Email',
        'qa.modal.btn_done': 'Hecho',
        'qa.modal.select_provider': 'Seleccionar Proveedor',
        'qa.modal.send_questions': 'Enviar Preguntas',
        'qa.toast.approved': 'Pregunta aprobada y añadida a la cola de Mail',
        'qa.toast.added': 'Pregunta añadida exitosamente',
        'qa.toast.exported': 'preguntas exportadas exitosamente a Excel',
        'qa.toast.sent': 'preguntas enviadas a',
        'qa.toast.link_copied': 'Enlace copiado al portapapeles',
        'qa.toast.copy_failed': 'Error al copiar. Por favor, copia manualmente.',
        'qa.toast.no_approved': 'No hay preguntas aprobadas para exportar. Por favor, aprueba algunas preguntas primero.',
        'qa.toast.no_questions': 'No hay preguntas para exportar',
        'qa.toast.select_both': 'Por favor selecciona un proyecto y un proveedor',
        'qa.toast.select_project': 'Por favor selecciona un proyecto en el formulario',
        'qa.toast.select_provider': 'Por favor selecciona un proveedor en el formulario',
        'qa.toast.enter_question': 'Por favor ingresa una pregunta',
        'qa.toast.project_error': 'No se pudo determinar el ID del proyecto. Por favor, reselecciona el proyecto.',
        'qa.toast.no_approved_provider': 'No hay preguntas aprobadas para {provider}. Por favor, aprueba algunas preguntas primero.',
        'qa.confirm.delete': '¿Estás seguro de que deseas eliminar esta pregunta?',

        // Disciplines
        'discipline.electrical': 'Eléctrico',
        'discipline.mechanical': 'Mecánico',
        'discipline.civil': 'Civil',
        'discipline.process': 'Proceso',
        'discipline.general': 'General',
        'discipline.cost': 'Costo',

        // Status
        'status.draft': 'Borrador',
        'status.pending': 'Pendiente',
        'status.approved': 'Aprobada',
        'status.sent': 'Enviada',
        'status.answered': 'Respondida',
        'status.resolved': 'Resuelta',
        'status.needs_more_info': 'Necesita Más Info',
        'status.discarded': 'Descartada',

        // Importance
        'importance.high': 'Alta',
        'importance.medium': 'Media',
        'importance.low': 'Baja',

        // Priority (for Q&A badges)
        'priority.high': 'Alta',
        'priority.medium': 'Media',
        'priority.low': 'Baja',

        // Common
        'common.questions': 'preguntas',
        'common.drafts': 'borradores',
        'common.high': 'alta',
        'common.project': 'Proyecto',
        'common.provider': 'Proveedor',
        'common.no_projects': 'No hay proyectos disponibles',

        // Scoring Matrix
        'scoring.title': 'Matriz de Puntuación de Proveedores',
        'scoring.subtitle': 'Puntuaciones evaluadas por IA en 12 criterios',
        'scoring.no_data': 'No hay datos de scoring disponibles',
        'scoring.no_data_hint': 'Haz clic en "Recalcular Scoring IA" para evaluar proveedores basándose en sus respuestas RFQ.',
        'scoring.loading': 'Calculando puntuaciones...',
        'scoring.category': 'Categoría',
        'scoring.criteria': 'Criterio',
        'scoring.final_scores': 'Puntuaciones Finales',
        'scoring.weighted_total': 'Total Ponderado',
        'scoring.last_updated': 'Última actualización',
        'scoring.total_weight': 'Total',
        'scoring.reset': 'Reiniciar',
        'scoring.save': 'Guardar',
        'scoring.saving': 'Guardando...',
        'scoring.recalculate': 'Recalcular Scoring IA',
        'scoring.calculating': 'Calculando...',
        'scoring.overall': 'PUNTUACIÓN TOTAL',
        'scoring.average': 'Promedio',
        'scoring.default': 'por defecto',

        // Charts
        'chart.compliant': 'Cumple',
        'chart.partial': 'Parcial',
        'chart.non_compliant': 'No Cumple',
        'chart.not_evaluated': 'No Evaluado',
        'chart.legend.compliant': 'Cumple',
        'chart.legend.partial': 'Cumple Parcialmente',
        'chart.legend.non_compliant': 'No Cumple',
        'chart.legend.not_evaluated': 'No Evaluado',
        'chart.types': 'tipos',
        'chart.loading_providers': 'Cargando proveedores...',
        'chart.connection_error': 'Error de conexión',
        'chart.could_not_load': 'No se pudieron cargar los datos',
        'chart.active_providers': 'Proveedores Activos',
        'chart.providers_with_data': 'proveedores con datos',
        'chart.no_data_configure': 'Sin datos - Configura Supabase',
        'chart.solution': 'Solución:',
        'chart.verify_supabase': 'Verifica la configuración de Supabase y que la tabla ranking_proveedores contenga datos.',
        'chart.total': 'Total',
        'chart.no_data': 'Sin datos',
        'chart.loading_data': 'Cargando datos...',
        'chart.rfq_distribution': 'Distribución de RFQs',
        'chart.total_requirements': 'requisitos totales',
        'chart.verify_supabase_rfq': 'Verifica la configuración de Supabase y que las tablas rfq_items_master y provider_responses contengan datos.',
        'chart.uncategorized': 'Sin categorizar',

        // Upload Dashboard additional
        'upload.doc_processed': 'Documento procesado exitosamente',
        'upload.ready_comparison': 'Listo para comparación',
        'upload.doc_overview': 'Resumen del Documento',
        'upload.requirements_analysis': 'Análisis de Requisitos',
        'upload.refreshing': 'Actualizando...',
        'upload.refresh_data': 'Actualizar datos del dashboard',
        'upload.rfq_by_type': 'Documentos RFQ por tipo de evaluación',
        'upload.auto_updates': 'Actualización automática cada 30s',
        'upload.ready_process': 'Listo para Procesar',
        'upload.upload_begin': 'Sube tus documentos RFQ para comenzar el análisis',
        'upload.distribution_desc': 'Distribución de documentos RFQ por tipo de evaluación en la base de datos',
        'upload.upload_see_breakdown': 'Sube un documento RFQ para ver el desglose por tipo de evaluación',
        'upload.click_view_status': 'Clic para ver estado de procesamiento',
        'upload.processing_files': 'Procesando {count} archivos...',

        // Sidebar processing indicator
        'sidebar.processing_files': 'Procesando {count} archivos...',
        'sidebar.click_view_status': 'Clic para ver estado de procesamiento',

        // Supplier Response Page
        'supplier.question': 'Pregunta',
        'supplier.followup_question': 'Pregunta de Seguimiento',
        'supplier.view_history': 'Ver historial de conversación',
        'supplier.hide_history': 'Ocultar historial',
        'supplier.previous_exchanges': 'intercambios anteriores',
        'supplier.previous_question': 'Pregunta Anterior',
        'supplier.your_previous_response': 'Tu Respuesta Anterior',
        'supplier.no_response': 'Sin respuesta proporcionada',

        // Chat Page
        'chat.clear_conversation': 'Limpiar conversación',
        'chat.loadingHistory': 'Cargando historial del chat...',
        'chat.welcome': '¿En qué puedo ayudarte?',
        'chat.copy_clipboard': 'Copiar al portapapeles',
        'chat.attach': 'Adjuntar',
        'chat.search': 'Buscar',

        // Data Table
        'table.title': 'Requisitos y Evaluaciones de Proveedores',
        'table.filters': 'Filtros',
        'table.csv': 'CSV',
        'table.excel': 'Excel',
        'table.rows': 'filas',
        'table.zoom': 'Zoom:',
        'table.project_name': 'Nombre del Proyecto',
        'table.select_project': 'Seleccionar Proyecto...',
        'table.evaluation_type': 'Tipo de Evaluación',
        'table.phase': 'Fase',
        'table.project': 'Proyecto',
        'table.requirement': 'Requisito',
        'table.clear_project_filter': 'Limpiar Filtro de Proyecto',
        'table.reload_data': 'Recargar Datos y Resetear Filtros',
        'table.no_results': 'No se encontraron resultados',
        'table.loading': 'Cargando datos...',

        // Proposal Upload Section
        'proposal.upload_title': 'Subir Documentos de Propuesta',
        'proposal.upload_subtitle': 'Selecciona archivos PDF y configura los metadatos individualmente',
        'proposal.processing_error': 'Error de Procesamiento',
        'proposal.remaining': 'Restantes',
        'proposal.upload_hint': 'Sube documentos de evaluación para aumentar el progreso',
        'proposal.select_provider': 'Selecciona un proveedor abajo para ver el progreso detallado',
        'proposal.provider_progress': 'Progreso de Proveedores',
        'proposal.provider_progress_hint': 'Haz clic en un proveedor para ver el estado de evaluación detallado',

        // FileUploadZone
        'dropzone.processing': 'Procesando propuestas... Esto puede tardar unos minutos',
        'dropzone.files_selected': '{count} archivos seleccionados ({size} MB total)',
        'dropzone.file_selected': '{name} ({size} MB)',
        'dropzone.drop_here': 'Suelta los archivos PDF aquí...',
        'dropzone.drag_compact': 'Arrastra archivos PDF o haz clic para seleccionar',
        'dropzone.drag_full': 'Arrastra y suelta archivos PDF aquí (hasta 7), o haz clic para seleccionar',
        'dropzone.configure_files': 'Configurar archivos ({count})',
        'dropzone.clear_all': 'Limpiar todo',

        // ProgressRing
        'progress.complete': 'completo',

        // Project Selector
        'project.enter_name': 'Por favor, ingresa un nombre de proyecto',
        'project.name_min_chars': 'El nombre del proyecto debe tener al menos 3 caracteres',
        'project.already_exists': 'Ya existe un proyecto con este nombre',
        'project.created_success': 'Proyecto creado exitosamente',
        'project.error_creating': 'Error al crear el proyecto',
        'project.loading': 'Cargando...',
        'project.select': 'Seleccionar Proyecto',
        'project.docs': 'docs',
        'project.no_projects': 'No se encontraron proyectos',
        'project.enter_name_placeholder': 'Ingresa el nombre del proyecto...',
        'project.create': 'Crear',
        'project.cancel': 'Cancelar',
        'project.new': 'Nuevo Proyecto'
    },
    en: {
        // ... existing translations
        // Sidebar
        'nav.home': 'Home',
        'nav.upload': 'Upload RFQ',
        'nav.table': 'Data Table',
        'nav.qa': 'Q&A Offers',
        'nav.decision': 'Scoring',
        'nav.chat': 'Chat',
        'nav.mail': 'Mail AI',
        'nav.footer': 'v2.1 Beta',

        // Header
        'header.home': 'Main Overview',
        'header.upload': 'RFQ & Proposal Management',
        'header.table': 'Data Explorer',
        'header.qa': 'Q&A & Offer Clarifications',
        'header.decision': 'Scoring Analysis',
        'header.chat': 'AI Assistant',
        'header.mail': 'Communication Generator',

        // Home Dashboard
        'home.hero.title': 'BidEval',
        'home.hero.subtitle': 'Intelligent Bid Evaluation Platform',
        'home.hero.desc': 'AI-powered bid evaluation. Smart analysis, automated scoring, and data-driven decisions.',
        'home.hero.btn_new': '+ New RFQ',
        'home.hero.btn_reports': 'View Reports',

        'home.stats.proposals': 'Processed Proposals',
        'home.stats.active': 'Active Projects',
        'home.stats.efficiency': 'AI Efficiency',
        'home.stats.trend_week': '+2 this week',
        'home.stats.trend_course': 'In progress',
        'home.stats.trend_high': 'High accuracy',

        'home.chart.title': 'Technical Compliance Status',
        'home.chart.subtitle': 'Last 30 days',
        'home.chart.evaluations_by_provider': 'Evaluations by Provider',
        'home.chart.distribution': 'Distribution of status in offers',

        'home.activity.title': 'Recent Activity',
        'home.activity.offer_received': 'Offer Received',
        'home.activity.offer_desc': 'Technical proposal automatically reviewed.',
        'home.activity.alert': 'Compliance Alert',
        'home.activity.alert_desc': 'missing HSE safety section.',
        'home.activity.created': 'New RFQ Created',
        'home.activity.created_desc': 'Green Hydrogen Project - Phase 2',
        'home.activity.user': 'User connected',
        'home.activity.ago_2h': '2 hours ago',
        'home.activity.ago_5h': '5 hours ago',
        'home.activity.yesterday': 'Yesterday',
        'home.activity.days_ago': 'days ago',
        'home.activity.just_now': 'Just now',
        'home.activity.proposal_evaluated': 'Proposal evaluated',
        'home.activity.qa_update': 'Q&A Update',
        'home.activity.qa_activity': 'Activity in Q&A module',
        'home.activity.recent_activity': 'Recent activity',
        'home.activity.no_activity': 'No recent activity',
        'home.activity.supplier_responded': 'Supplier Response',
        'home.activity.questions_sent': 'Questions Sent',
        'home.activity.evaluation_updated': 'Evaluation Updated',
        'home.activity.response_received': 'response(s) received',

        // Dashboard cards
        'home.card.total_processed': 'Proposals Processed',
        'home.card.rfqs_processed': 'RFQs Processed',
        'home.card.ai_accuracy': 'AI Accuracy',
        'home.card.automation': 'Automation',
        'home.card.this_week': 'this week',
        'home.card.proposals': 'proposals',
        'home.card.coverage': 'coverage',
        'home.card.excellent_performance': 'Excellent performance',
        'home.card.very_high': 'Very high',
        'home.card.avg_time': 'Average Time',
        'home.card.completed_today': 'Completed Today',
        'home.card.active_providers': 'Active Providers',

        // AI Scoring section
        'home.scoring.title': 'AI Scoring by Provider',
        'home.scoring.subtitle': 'Weighted scores from workflow',
        'home.scoring.top_performer': 'Top Performer',
        'home.scoring.avg_score': 'Average Score',
        'home.scoring.compliance_rate': 'Compliance Rate',
        'home.scoring.providers_evaluated': 'Providers Evaluated',
        'home.scoring.no_data': 'No scoring data available. Run AI Scoring to generate results.',
        'home.scoring.technical': 'Technical',
        'home.scoring.economic': 'Economic',
        'home.scoring.execution': 'Execution',
        'home.scoring.hse': 'HSE',

        // Vendor Decision Dashboard
        'dashboard.title': 'Vendor Scoring Dashboard',
        'dashboard.rfq_id': 'RFQ ID',
        'dashboard.tab.clarification': 'Clarification & Q&A',
        'dashboard.tab.scoring': 'Scoring Matrix',
        'dashboard.tab.executive': 'Executive Summary',
        'dashboard.loading': 'Loading Scoring Analysis...',
        // Clarification View
        'clarification.filter': 'Filter by Provider',
        'clarification.table.req': 'Requirement',
        'clarification.table.resp': 'Provider Response',
        'clarification.table.comp': 'Compliance',
        'clarification.table.actions': 'Clarification & Actions',
        'clarification.btn.send': 'Send Question',
        'clarification.btn.approve': 'Approve Question',
        'clarification.btn.resolve': 'Mark Resolved',
        'clarification.status.resolved': '✓ Resolved',
        'clarification.export': 'Export Q&A Sheet (.xlsx)',

        // Scoring View
        'scoring.req': 'Requirement',
        'scoring.weight': 'Weight',
        'scoring.total': 'Weighted Score',

        // Executive View
        'executive.winner': 'Recommended Winner',
        'executive.score': 'Score',
        'executive.award': 'Award Contract',
        'executive.radar.title': 'Category Comparison',
        'executive.bar.title': 'Final Weighted Scores',
        'executive.radar.subtitle': 'Multidimensional comparison by category',
        'executive.bar.subtitle': 'Total weighted score',
        'executive.calculating': 'Calculating AI Scores...',
        'executive.calculating_subtitle': 'Evaluating providers across 12 criteria. This may take a moment.',
        'executive.no_data': 'No scoring data available. Run the scoring workflow to generate results.',
        'executive.refresh': 'Refresh Data',
        'executive.lead_margin': 'Lead Margin vs',
        'executive.pts': 'pts',
        'executive.advantage': 'advantage',
        'executive.key_strengths': 'Key Strengths',
        'executive.no_strengths': 'No dominant categories',
        'executive.areas_review': 'Areas to Review',
        'executive.no_data_available': 'No data available',
        'executive.top_rankings': 'Top Rankings',
        'executive.criteria_weight': 'Criteria Weight Distribution',
        'executive.scoring_impact': 'Scoring impact by category',
        'executive.weight': 'Weight',
        'executive.contract_awarded': 'Contract awarded to',
        'executive.total_score': 'Total Score',
        // Category names
        'category.technical': 'TECHNICAL',
        'category.economic': 'ECONOMIC',
        'category.execution': 'EXECUTION',
        'category.hse_compliance': 'HSE & COMPLIANCE',
        // Criteria labels
        'criteria.scope_facilities': 'Scope of Facilities',
        'criteria.scope_work': 'Scope of Work',
        'criteria.deliverables_quality': 'Deliverables Quality',
        'criteria.total_price': 'Total Price',
        'criteria.price_breakdown': 'Price Breakdown',
        'criteria.optionals_included': 'Optionals Included',
        'criteria.capex_opex_methodology': 'CAPEX/OPEX Methodology',
        'criteria.schedule': 'Schedule',
        'criteria.resources_allocation': 'Resources Allocation',
        'criteria.exceptions': 'Exceptions',
        'criteria.safety_studies': 'Safety Studies',
        'criteria.regulatory_compliance': 'Regulatory Compliance',
        // Criteria descriptions
        'criteria.scope_facilities.desc': 'Hydrogen plant, BOP, utilities included',
        'criteria.scope_work.desc': 'Project management, studies, deliverables covered',
        'criteria.deliverables_quality.desc': 'P&IDs, specifications, 3D model quality',
        'criteria.total_price.desc': 'PRE-FEED + FEED + EPC price competitiveness',
        'criteria.price_breakdown.desc': 'Transparent hours/discipline and €/hour',
        'criteria.optionals_included.desc': 'Geotechnical, topographic, 3D, HAZID in base price',
        'criteria.capex_opex_methodology.desc': 'AACEI class offered, estimate robustness',
        'criteria.schedule.desc': 'Realistic timeline vs requirements',
        'criteria.resources_allocation.desc': 'Coherent hours per discipline',
        'criteria.exceptions.desc': 'Fewer exceptions and deviations = better',
        'criteria.safety_studies.desc': 'HAZID, HAZOP, QRA, ATEX included',
        'criteria.regulatory_compliance.desc': 'Codes, standards, safety distances',
        // Scoring matrix categories
        'scoring.category.technical': 'TECHNICAL',
        'scoring.category.economic': 'ECONOMIC',
        'scoring.category.execution': 'EXECUTION',
        'scoring.category.hse_compliance': 'HSE & COMPLIANCE',

        // Upload & App
        'upload.error.file_size': 'file(s) too large. Max',
        'upload.confirm.delete': 'Are you sure you want to delete the loaded base RFQ?',
        'upload.rfq_loaded': 'RFQ Loaded',
        'upload.processed_types': 'Types',
        'upload.change_rfq': 'Change RFQ',
        'upload.rfq_hint': 'The requirements from this RFQ will be used to compare with provider proposals',
        'upload.modal.replace_title': 'Replace current RFQ?',
        'upload.modal.current': 'You already have an RFQ loaded',
        'upload.modal.replace_bg': 'Do you want to replace it with',
        'upload.files': 'RFQ files',
        'upload.btn.replace': 'Yes, replace',
        'upload.btn.cancel': 'Cancel',
        'upload.status.processing': 'Processing RFQ... This may take a few minutes',
        'upload.files_selected': 'files selected',
        'upload.drop_here': 'Drop PDF files here...',
        'upload.drag_drop': 'Drag and drop RFQ PDFs here, or click to select',
        'upload.view_files': 'View files',
        'upload.status.error': 'Error',
        'upload.file': 'file',
        'upload.btn.process': 'Process',
        'upload.btn.reset': 'Reset',
        'upload.modal.files_title': 'Selected RFQ Files',
        'upload.btn.close': 'Close',
        'upload.btn.remove': 'Remove file',
        'upload.btn.clear_all': 'Clear all files',
        'app.upload.tab.rfq': '1. Upload Reference RFQ',
        'app.upload.tab.proposals': '2. Upload Provider Proposals',
        'app.upload.supported_providers': 'Supported providers: Técnicas Reunidas, IDOM, SACYR, Empresarios Agrupados, SENER, TRESCA, WORLEY',
        'common.error': 'Error',
        'upload.proposals': 'Proposals',
        'common.reset': 'Reset',
        'app.table.no_data': 'No processed data yet. Go to "Upload & Process" section to start.',
        'chat.placeholder': 'Ask me anything...',

        // Mail Dashboard
        'mail.config': 'Mail Configuration',
        'mail.project': 'Project',
        'mail.provider': 'Recipient Provider',
        'mail.provider.select': 'Select Provider...',
        'mail.tone': 'Tone',
        'mail.tone.formal': 'Formal',
        'mail.tone.urgent': 'Urgent',
        'mail.tone.friendly': 'Friendly',
        'mail.btn.drafting': 'Drafting Email...',
        'mail.btn.regenerate': 'Regenerate Draft',
        'mail.btn.generate': 'Generate Draft',
        'mail.empty.title': 'Ready to Draft',
        'mail.empty.desc': 'Select a provider to generate a professional email draft powered by AI.',
        'mail.preview.markdown': 'Markdown',
        'mail.preview.text': 'Text',
        'mail.btn.discard': 'Discard',
        'mail.btn.copy': 'Copy to Clipboard',
        'mail.preview.header': 'Draft Preview',
        'mail.preview.to': 'To:',
        'mail.preview.subject': 'Subject:',
        'mail.tech_questions': 'Technical Questions',
        'mail.btn.all': 'All',
        'mail.btn.none': 'None',
        'mail.no_qa_items': 'No Q&A items for',
        'mail.other_items': 'items for other providers',
        'mail.ai_drafting': 'AI Agent is drafting your email...',
        'mail.analyzing': 'Analyzing context and formatting issues',
        'mail.generation_failed': 'Generation Failed',
        'mail.generation_failed_desc': 'Failed to generate draft. Please try again.',
        'mail.btn.done': 'Done',
        'mail.btn.edit': 'Edit',
        'mail.btn.send': 'Send Email',
        'mail.btn.sending': 'Sending...',
        'mail.btn.sent': 'Sent!',
        'mail.btn.copy_short': 'Copy',
        'mail.tone_label': 'Tone',
        'mail.alert.enter_email': 'Please enter a valid email address in the "To" field.',
        'mail.alert.confirm_send': 'Send email to',
        'mail.alert.copy_success': 'Email copied to clipboard!',
        'mail.alert.send_success': 'Email sent successfully!',
        'mail.alert.send_failed': 'Failed to send email. Please try again or copy and send manually.',
        'mail.recipient_placeholder': 'recipient@email.com',

        // Analysis Columns
        'table.col.requirement': 'Requirement',
        'table.col.phase': 'Phase',
        'table.col.evaluation': 'Evaluation',
        'table.col.description': 'Item Description',

        // Tour / Onboarding
        'tour.welcome.title': 'Welcome to BidEval',
        'tour.welcome.description': 'We\'ll guide you through the main features of the platform so you can get the most out of it.',
        'tour.sidebar.title': 'Main Navigation',
        'tour.sidebar.description': 'This is the sidebar menu where you\'ll find access to all platform modules. You can expand or collapse it. Visual indicators show modules with active sessions.',
        'tour.home.title': 'Dashboard',
        'tour.home.description': 'Here you\'ll see a summary of your activity: metrics, statistics, and recent activity from your projects.',
        'tour.upload.title': 'Upload Documents',
        'tour.upload.description': 'Upload your reference RFQs and vendor proposals. The system will automatically process and extract requirements.',
        'tour.table.title': 'Data Explorer',
        'tour.table.description': 'View and explore all processed data in table format with advanced filters and export options.',
        'tour.qa.title': 'Offer Q&A',
        'tour.qa.description': 'Manage pending questions and clarifications about vendor offers.',
        'tour.decision.title': 'Scoring Analysis',
        'tour.decision.description': 'Scoring matrix with comparative vendor analysis. Adjust weights and view the final ranking.',
        'tour.chat.title': 'AI Assistant',
        'tour.chat.description': 'Chat with our intelligent assistant to get quick answers about your RFQs and proposals.',
        'tour.mail.title': 'Email Generator',
        'tour.mail.description': 'Generate professional email drafts with AI based on pending clarifications for each vendor.',
        'tour.project.title': 'Project Selection',
        'tour.project.description': 'Here you can switch between your active projects. Changing the project will update all dashboard information accordingly.',
        'tour.header.title': 'Quick Settings',
        'tour.header.description': 'Change language, toggle between light and dark mode, and access your profile from here.',
        'tour.finish.title': 'Ready to go!',
        'tour.finish.description': 'You now know the main features. You can restart this tour anytime from the help menu.',
        'tour.btn.next': 'Next',
        'tour.btn.back': 'Back',
        'tour.btn.skip': 'Skip tour',
        'tour.btn.finish': 'Finish',
        'tour.btn.close': 'Close',
        'tour.btn.restart': 'Restart Tour',

        // Notifications
        'notifications.title': 'Notifications',
        'notifications.markAllRead': 'Mark all as read',
        'notifications.clearAll': 'Clear all',
        'notifications.delete': 'Delete',
        'notifications.empty': 'No notifications',
        'notifications.supplierResponded': 'Supplier has responded',
        'notifications.evaluationUpdated': 'Evaluation updated',
        'notifications.questionsSent': 'Questions sent',

        // QA Module
        'qa.title': 'Q&A Management',
        'qa.subtitle': 'Generate intelligent questions and manage technical audits',
        'qa.generator.title': 'Technical Audit Generator',
        'qa.generator.subtitle': 'Generate AI-powered questions based on provider deficiencies',
        'qa.generator.project': 'Project',
        'qa.generator.provider': 'Provider',
        'qa.generator.select_project': 'Select project...',
        'qa.generator.select_provider': 'Select Provider',
        'qa.generator.btn_generate': 'Generate Technical Audit',
        'qa.generator.btn_generating': 'Generating Audit...',
        'qa.generator.btn_export': 'Export to Excel',
        'qa.generator.status_analyzing': 'Analyzing deficiencies and generating technical audit questions...',
        'qa.questions.title': 'Questions Management',
        'qa.questions.subtitle': 'View and manage generated questions by discipline',
        'qa.questions.btn_send': 'Send to Supplier',
        'qa.questions.btn_sending': 'Sending...',
        'qa.questions.btn_export_all': 'Export All Questions',
        'qa.questions.btn_filters': 'Filters',
        'qa.questions.total': 'Total Questions',
        'qa.questions.approved': 'Approved',
        'qa.questions.pending': 'Pending',
        'qa.questions.high_importance': 'High Importance',
        'qa.questions.no_questions': 'No questions generated',
        'qa.questions.no_questions_hint': 'Select a project and provider, then click "Generate Technical Audit"',
        'qa.questions.add_question': '+ Add another question',
        'qa.questions.write_question': 'Write your question here...',
        'qa.questions.view_source': 'View source requirement',
        'qa.questions.loading_req': 'Loading requirement...',
        'qa.question.response': 'Response:',
        'qa.question.answered_on': 'Answered on',
        'qa.question.internal_notes': 'Internal notes:',
        'qa.btn.edit': 'Edit',
        'qa.btn.save': 'Save',
        'qa.btn.cancel': 'Cancel',
        'qa.btn.approve': 'Approve',
        'qa.btn.discard': 'Discard',
        'qa.btn.send': 'Send',
        'qa.btn.accept_response': 'Accept Response',
        'qa.btn.need_more_info': 'Need More Info',
        'qa.btn.mark_resolved': 'Mark Resolved',
        'qa.status.waiting': 'Waiting for response...',
        'qa.status.review_needed': 'Response received - Review needed',
        'qa.status.resolved': '✓ Response accepted - Issue resolved',
        'qa.status.more_info': 'Additional clarification requested',
        'qa.status.discarded': 'Discarded',
        // Thread/Conversation translations
        'qa.thread.follow_up': 'Follow-up Question',
        'qa.thread.write_follow_up': 'Write your follow-up question based on the supplier response...',
        'qa.thread.send_follow_up': 'Send Follow-up',
        'qa.thread.conversation': 'Conversation',
        'qa.thread.original_question': 'Original Question',
        'qa.thread.resolved': 'Thread Resolved',
        'qa.thread.follow_up_label': 'Follow-up',
        'qa.thread.view_thread': 'View conversation',
        'qa.thread.collapse_thread': 'Hide conversation',
        'qa.thread.created_draft': 'Follow-up question created as draft. Approve and send it together with others.',
        'qa.thread.view_history': 'View conversation history',
        'qa.thread.hide_history': 'Hide thread',
        'qa.thread.previous_question': 'Question',
        'qa.thread.previous_response': 'Supplier response',
        'qa.thread.no_response_yet': 'No response yet',
        'qa.thread.current_question': 'Current question (below)',
        'qa.thread.no_history': 'Could not load history',
        'qa.badge.original': 'Original',
        'qa.filters.title': 'Search Filters',
        'qa.filters.clear': 'Clear All',
        'qa.filters.provider': 'Provider',
        'qa.filters.all_providers': 'All Providers',
        'qa.filters.status': 'Status',
        'qa.filters.all_statuses': 'All Statuses',
        'qa.filters.importance': 'Importance',
        'qa.filters.all_importances': 'All Importances',
        'qa.modal.success_title': 'Questions Sent Successfully',
        'qa.modal.success_subtitle': 'The questionnaire has been prepared for',
        'qa.modal.questions': 'Questions',
        'qa.modal.provider': 'Provider',
        'qa.modal.expires': 'Expires',
        'qa.modal.link_label': 'Response Link (share with supplier)',
        'qa.modal.link_hint': 'Send this link to the supplier. They can access the questionnaire and submit their responses.',
        'qa.modal.email_preview': 'Email Preview',
        'qa.modal.btn_done': 'Done',
        'qa.modal.select_provider': 'Select Provider',
        'qa.modal.send_questions': 'Send Questions',
        'qa.toast.approved': 'Question approved and added to Mail queue',
        'qa.toast.added': 'Question added successfully',
        'qa.toast.exported': 'questions exported successfully to Excel',
        'qa.toast.sent': 'questions sent to',
        'qa.toast.link_copied': 'Link copied to clipboard',
        'qa.toast.copy_failed': 'Failed to copy link. Please copy manually.',
        'qa.toast.no_approved': 'No approved questions to export. Please approve some questions first.',
        'qa.toast.no_questions': 'No questions to export',
        'qa.toast.select_both': 'Please select a project and a provider',
        'qa.toast.select_project': 'Please select a project in the form above',
        'qa.toast.select_provider': 'Please select a provider in the form above',
        'qa.toast.enter_question': 'Please enter a question',
        'qa.toast.project_error': 'Could not determine project ID. Please reselect the project.',
        'qa.toast.no_approved_provider': 'No approved questions for {provider}. Please approve some questions first.',
        'qa.confirm.delete': 'Are you sure you want to delete this question?',

        // Disciplines
        'discipline.electrical': 'Electrical',
        'discipline.mechanical': 'Mechanical',
        'discipline.civil': 'Civil',
        'discipline.process': 'Process',
        'discipline.general': 'General',
        'discipline.cost': 'Cost',

        // Status
        'status.draft': 'Draft',
        'status.pending': 'Pending',
        'status.approved': 'Approved',
        'status.sent': 'Sent',
        'status.answered': 'Answered',
        'status.resolved': 'Resolved',
        'status.needs_more_info': 'Needs More Info',
        'status.discarded': 'Discarded',

        // Importance
        'importance.high': 'High',
        'importance.medium': 'Medium',
        'importance.low': 'Low',

        // Priority (for Q&A badges)
        'priority.high': 'High',
        'priority.medium': 'Medium',
        'priority.low': 'Low',

        // Common
        'common.questions': 'questions',
        'common.drafts': 'drafts',
        'common.high': 'high',
        'common.project': 'Project',
        'common.provider': 'Provider',
        'common.no_projects': 'No projects available',

        // Scoring Matrix
        'scoring.title': 'Provider Scoring Matrix',
        'scoring.subtitle': 'AI-evaluated scores across 12 criteria',
        'scoring.no_data': 'No Scoring Data Available',
        'scoring.no_data_hint': 'Click "Recalculate AI Scoring" to evaluate providers based on their RFQ responses.',
        'scoring.loading': 'Calculating scores...',
        'scoring.category': 'Category',
        'scoring.criteria': 'Criterion',
        'scoring.final_scores': 'Final Scores',
        'scoring.weighted_total': 'Weighted Total',
        'scoring.last_updated': 'Last updated',
        'scoring.total_weight': 'Total',
        'scoring.reset': 'Reset',
        'scoring.save': 'Save',
        'scoring.saving': 'Saving...',
        'scoring.recalculate': 'Recalculate AI Scoring',
        'scoring.calculating': 'Calculating...',
        'scoring.overall': 'OVERALL SCORE',
        'scoring.average': 'Average',
        'scoring.default': 'default',

        // Charts
        'chart.compliant': 'Compliant',
        'chart.partial': 'Partial',
        'chart.non_compliant': 'Non-Compliant',
        'chart.not_evaluated': 'Not Evaluated',
        'chart.legend.compliant': 'Compliant',
        'chart.legend.partial': 'Partially Compliant',
        'chart.legend.non_compliant': 'Non-Compliant',
        'chart.legend.not_evaluated': 'Not Evaluated',
        'chart.types': 'types',
        'chart.loading_providers': 'Loading providers...',
        'chart.connection_error': 'Connection error',
        'chart.could_not_load': 'Could not load data',
        'chart.active_providers': 'Active Providers',
        'chart.providers_with_data': 'providers with data',
        'chart.no_data_configure': 'No data - Configure Supabase',
        'chart.solution': 'Solution:',
        'chart.verify_supabase': 'Check Supabase configuration and ensure ranking_proveedores table has data.',
        'chart.total': 'Total',
        'chart.no_data': 'No data',
        'chart.loading_data': 'Loading data...',
        'chart.rfq_distribution': 'RFQ Distribution',
        'chart.total_requirements': 'total requirements',
        'chart.verify_supabase_rfq': 'Check Supabase configuration and ensure rfq_items_master and provider_responses tables have data.',
        'chart.uncategorized': 'Uncategorized',

        // Upload Dashboard additional
        'upload.doc_processed': 'Document processed successfully',
        'upload.ready_comparison': 'Ready for comparison',
        'upload.doc_overview': 'Document Overview',
        'upload.requirements_analysis': 'Requirements Analysis',
        'upload.refreshing': 'Refreshing...',
        'upload.refresh_data': 'Refresh dashboard data',
        'upload.rfq_by_type': 'RFQ documents by evaluation type',
        'upload.auto_updates': 'Auto-updates every 30s',
        'upload.ready_process': 'Ready to Process',
        'upload.upload_begin': 'Upload your RFQ documents to begin analysis',
        'upload.distribution_desc': 'Distribution of RFQ documents across evaluation types in the database',
        'upload.upload_see_breakdown': 'Upload an RFQ document to see its evaluation type breakdown',
        'upload.click_view_status': 'Click to view processing status',
        'upload.processing_files': 'Processing {count} files...',

        // Sidebar processing indicator
        'sidebar.processing_files': 'Processing {count} files...',
        'sidebar.click_view_status': 'Click to view processing status',

        // Supplier Response Page
        'supplier.question': 'Question',
        'supplier.followup_question': 'Follow-up Question',
        'supplier.view_history': 'View conversation history',
        'supplier.hide_history': 'Hide history',
        'supplier.previous_exchanges': 'previous exchanges',
        'supplier.previous_question': 'Previous Question',
        'supplier.your_previous_response': 'Your Previous Response',
        'supplier.no_response': 'No response provided',

        // Chat Page
        'chat.clear_conversation': 'Clear Conversation',
        'chat.loadingHistory': 'Loading chat history...',
        'chat.welcome': 'How can I help you?',
        'chat.copy_clipboard': 'Copy to clipboard',
        'chat.attach': 'Attach',
        'chat.search': 'Search',

        // Data Table
        'table.title': 'Requirements & Provider Evaluations',
        'table.filters': 'Filters',
        'table.csv': 'CSV',
        'table.excel': 'Excel',
        'table.rows': 'rows',
        'table.zoom': 'Zoom:',
        'table.project_name': 'Project Name',
        'table.select_project': 'Select Project...',
        'table.evaluation_type': 'Evaluation Type',
        'table.phase': 'Phase',
        'table.project': 'Project',
        'table.requirement': 'Requirement',
        'table.clear_project_filter': 'Clear Project Filter',
        'table.reload_data': 'Reload Data & Reset Filters',
        'table.no_results': 'No results found',
        'table.loading': 'Loading data...',

        // Proposal Upload Section
        'proposal.upload_title': 'Upload Proposal Documents',
        'proposal.upload_subtitle': 'Select PDF files and configure metadata for each file individually',
        'proposal.processing_error': 'Processing Error',
        'proposal.remaining': 'Remaining',
        'proposal.upload_hint': 'Upload evaluation documents to increase progress',
        'proposal.select_provider': 'Select a provider below to view detailed progress',
        'proposal.provider_progress': 'Provider Progress',
        'proposal.provider_progress_hint': 'Click on a provider to view detailed evaluation status',

        // FileUploadZone
        'dropzone.processing': 'Processing proposals... This may take a few minutes',
        'dropzone.files_selected': '{count} files selected ({size} MB total)',
        'dropzone.file_selected': '{name} ({size} MB)',
        'dropzone.drop_here': 'Drop the PDF files here...',
        'dropzone.drag_compact': 'Drag PDF files or click to select',
        'dropzone.drag_full': 'Drag and drop PDF files here (up to 7), or click to select',
        'dropzone.configure_files': 'Configure files ({count})',
        'dropzone.clear_all': 'Clear all',

        // ProgressRing
        'progress.complete': 'complete',

        // Project Selector
        'project.enter_name': 'Please enter a project name',
        'project.name_min_chars': 'Project name must be at least 3 characters',
        'project.already_exists': 'A project with this name already exists',
        'project.created_success': 'Project created successfully',
        'project.error_creating': 'Error creating project',
        'project.loading': 'Loading...',
        'project.select': 'Select Project',
        'project.docs': 'docs',
        'project.no_projects': 'No projects found',
        'project.enter_name_placeholder': 'Enter project name...',
        'project.create': 'Create',
        'project.cancel': 'Cancel',
        'project.new': 'New Project'
    }
};

// Get initial language from localStorage or default to 'en'
const getInitialLanguage = (): Language => {
    if (typeof window !== 'undefined') {
        const saved = localStorage.getItem('bideval-language');
        if (saved === 'es' || saved === 'en') {
            return saved;
        }
    }
    return 'en';
};

export const useLanguageStore = create<LanguageState>((set, get) => ({
    language: getInitialLanguage(),
    setLanguage: (lang) => {
        // Save to localStorage when user changes language
        if (typeof window !== 'undefined') {
            localStorage.setItem('bideval-language', lang);
        }
        set({ language: lang });
    },
    t: (key) => {
        const lang = get().language;
        // @ts-ignore
        const text = translations[lang][key];

        // Fallback to English if translation missing in Spanish
        if (!text && lang !== 'en') {
            // @ts-ignore
            return translations['en'][key] || key;
        }

        return text || key;
    }
}));
