import type { Disciplina as DisciplinaType, EstadoPregunta as EstadoPreguntaType, Importancia as ImportanciaType } from './database.types';

/**
 * Types for the Q&A & Technical Audit module
 */

// Re-export types to facilitate imports
export type Disciplina = DisciplinaType;
export type EstadoPregunta = EstadoPreguntaType;
export type Importancia = ImportanciaType;

// Question generated by AI (mapped from qa_audit table)
export interface QAQuestion {
  id: string;
  created_at: string;
  project_name: string; // Mapped from project_id
  provider_name: string; // Mapped from provider
  discipline: Disciplina; // Mapped from discipline
  question: string; // Mapped from pregunta_texto
  status: EstadoPregunta; // Mapped from estado
  importance?: Importancia | null; // Mapped from importancia
  response?: string | null; // Mapped from respuesta_proveedor
  parent_question_id?: string | null; // For thread/conversation support
  // Additional fields for frontend compatibility
  project_id?: string; // Alias of project_name
  proveedor?: string; // Alias of provider_name
  disciplina?: Disciplina; // Alias of discipline
  pregunta_texto?: string; // Alias of question
  estado?: EstadoPregunta; // Alias of status
  importancia?: Importancia | null; // Alias of importance
  respuesta_proveedor?: string | null; // Alias of response
  fecha_respuesta?: string | null; // Not in table but maintained by frontend
  notas_internas?: string | null; // Not in table but maintained by frontend
  requirement_id?: string | null; // From qa_audit table
}

// Structure of the qa_audit table in the database
export interface QAAuditDB {
  id: string;
  created_at: string;
  project_name: string;
  provider_name: string;
  discipline: Disciplina;
  question: string;
  status: EstadoPregunta;
  importance?: Importancia | null;
  response?: string | null;
  requirement_id?: string | null;
  parent_question_id?: string | null; // For thread/conversation support
}

// Function to map from DB to frontend
export function mapQAAuditToQAQuestion(dbItem: QAAuditDB): QAQuestion {
  return {
    ...dbItem,
    // Original fields from DB
    project_name: dbItem.project_name,
    provider_name: dbItem.provider_name,
    discipline: dbItem.discipline,
    question: dbItem.question,
    status: dbItem.status,
    importance: dbItem.importance,
    response: dbItem.response,
    parent_question_id: dbItem.parent_question_id,
    // Alias for frontend compatibility
    project_id: dbItem.project_name,
    proveedor: dbItem.provider_name,
    disciplina: dbItem.discipline,
    pregunta_texto: dbItem.question,
    estado: dbItem.status,
    importancia: dbItem.importance,
    respuesta_proveedor: dbItem.response,
  };
}

// Function to map from frontend to DB
export function mapQAQuestionToQAAudit(frontendItem: Partial<QAQuestion>): Partial<QAAuditDB> {
  return {
    id: frontendItem.id,
    created_at: frontendItem.created_at,
    project_name: frontendItem.project_name || frontendItem.project_id,
    provider_name: frontendItem.provider_name || frontendItem.proveedor,
    discipline: frontendItem.discipline || frontendItem.disciplina,
    question: frontendItem.question || frontendItem.pregunta_texto,
    status: frontendItem.status || frontendItem.estado,
    importance: frontendItem.importance || frontendItem.importancia,
    response: frontendItem.response || frontendItem.respuesta_proveedor,
    requirement_id: frontendItem.requirement_id,
    parent_question_id: frontendItem.parent_question_id,
  };
}

// Filters for the module
export interface QAFilters {
  proveedor?: string | null;
  disciplina?: Disciplina | null;
  estado?: EstadoPregunta | null;
  importancia?: Importancia | null;
}

// Statistics by discipline
export interface DisciplinaStats {
  disciplina: Disciplina;
  total: number;
  porEstado: Record<EstadoPregunta, number>;
  porImportancia: Record<Importancia, number>;
}

// Payload for the n8n webhook (audit generation)
export interface GenerateAuditPayload {
  project_id: string;      // UUID del proyecto
  project_name?: string;   // Nombre display del proyecto
  provider: string;
}

// Response from the n8n webhook
export interface GenerateAuditResponse {
  success: boolean;
  preguntas_generadas: number;
  message?: string;
  data?: any[];
}

// Available actions for a question
export type QAAction = 'edit' | 'approve' | 'discard' | 'send' | 'delete';

// Grouped view by discipline
export interface DisciplinaGroup {
  disciplina: Disciplina;
  preguntas: QAQuestion[];
  stats: {
    total: number;
    borradores: number;
    aprobadas: number;
    pendientes: number;
    alta: number;
    media: number;
    baja: number;
  };
}
